apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-web-odon-track-ingress
spec:
  rules:
  - host: app-web.local  # Este é o domínio que você usará no navegador
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-web-odon-track
            port:
              number: 4200
