apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-odontrack-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-odon-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api-odon-track
  template:
    metadata:
      labels:
        app: app-api-odon-track
    spec:
      containers:
        - name: app-api-odon-track
          image: app-api-odon-track-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ConnOdonTrack
              value: "server=mysql-service;port=3306;database=odon_track;User=root;Password=2rQ78h$32T@4f7gy="
            - name: ApiPython
              value: "http://app-odon-track-python-api:5000"
            - name: NumeroUnifenas
              value: "(35) 98888-8888"
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:80"
          volumeMounts:
            - name: imagens
              mountPath: /app/imagens-prontuario
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: api-odontrack-pvc