apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-odon-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api-odon-track
  template:
    metadata:
      labels:
        app: app-api-odon-track
    spec:
      containers:
      - name: app-api-odon-track
        imagePullPolicy: IfNotPresent
        image: app-api-odon-track-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnOdonTrack
          value: "server=mysql-service;port=3306;database=odon_track;User=root;Password=2rQ78h$32T@4f7gy=;"
