apiVersion: v1
kind: Service
metadata:
  name: app-api-odon-track
spec:
  selector:
    app: app-api-odon-track
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
