apiVersion: v1
kind: Pod
metadata:
  name: odon-track-pod
spec:
  containers:
    - name: odon-track-pod
      image: odon-track-pod:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
